#!/usr/bin/env python3
from __future__ import annotations
from pathlib import Path
from pprint import pformat
import re, yaml
ROOT=Path(__file__).resolve().parents[1]
SRC="CORPUS-SRC-101"; WIT="CORPUS-WIT-101"; STUDY="PROGRESS-RETURN-STUDY-001"; CSTUDY="CORPUS-STUDY-016"
SPATH="studies/theologico-political/progress-or-return/sequential-reconstruction.yaml"
TP="problems/theologico-political/synthesis/progress-or-return.yaml"; AVJ="problems/athens-vs-jerusalem/synthesis/progress-or-return.yaml"; AVM="problems/ancients-vs-moderns/synthesis/progress-or-return.yaml"
def load(p):
    with (ROOT/p).open(encoding='utf-8') as f:return yaml.safe_load(f)
def dump(p,d):(ROOT/p).write_text(yaml.safe_dump(d,sort_keys=False,allow_unicode=True,width=110),encoding='utf-8')
def uniq(xs):
    o=[]
    for x in xs:
        if x not in o:o.append(x)
    return o

def corpus():
    p='corpus/index.yaml'; d=load(p); d['identity']['version']='1.17.0'; d['revision_history']={'predecessor_version':'1.16.0','predecessor_blob_sha':'PRESERVED_BY_GIT','transformation':'SUBSTANTIVE_FORWARD_REVISION','reason':'Register PROGRESS-RETURN-STUDY-001 as the ninth complete provisional Theologico-Political item study, correct CORPUS-SRC-101 publication provenance to the 1952 lectures and 1979/1981 posthumous publication history supplied by the reviewed collection, and preserve noncorroboration, noncertification, predecessor authority, and no successor effect.'}
    s=next(x for x in d['source_entities'] if x['source_id']==SRC); s['study_records']=[CSTUDY]; s['item_level_source_status']='REVIEWED_ITEM_WITNESS_REGISTERED_AND_COMPLETE_PROVISIONAL_SEQUENTIAL_RECONSTRUCTION'; s['study_status']='COMPLETE_PROVISIONAL_FOR_REVIEWED_1997_COLLECTED_WITNESS'; s['limits']=['reviewed witness is the fingerprinted 1997 SUNY collected text, not separately reviewed 1979 or 1981 posthumous publications','printed pages 87-136 correspond to one-based PDF pages 106-155','Strauss lecture and discussion body occupies printed pages 87-132 and editorial notes continue through 136','PROGRESS-RETURN-STUDY-001 is source-local and not independent corroboration of biblical, Greek, Jewish, Christian, Spinozist, or modern historical claims','the act-of-faith formulation remains source-local and the revelation-philosophy conflict remains unresolved']
    e=next(x for x in d['source_status_records'] if x['source_id']==SRC); e['completion']='REVIEWED_ITEM_WITNESS_REGISTERED_AND_COMPLETE_PROVISIONAL_SEQUENTIAL_RECONSTRUCTION'
    if not any(x.get('study_id')==CSTUDY for x in d['study_records']): d['study_records'].append({'study_id':CSTUDY,'source_id':SRC,'path':SPATH,'record_role':'SOURCE_SPECIFIC_SEQUENTIAL_RECONSTRUCTION','completion':'COMPLETE_PROVISIONAL_FOR_REVIEWED_1997_COLLECTED_WITNESS','certification':'NOT_CERTIFIED'})
    c=d['coverage']; c['study_records_registered']=16; c['theologico_political_independent_item_studies_registered']=9; c['current_studies_tree_yaml_records_accounted_for']=56
    next(x for x in d['corpus_gaps'] if x['gap_id']=='CORPUS-GAP-003')['statement']='All nineteen predecessor writings have bounded source identities and reviewed item witnesses; nine have complete provisional sequential studies, while the remaining ten lack independent item studies.'
    d['validation_rules']=uniq([x for x in d['validation_rules'] if 'witness-only Theologico-Political sources' not in x]+['CORPUS-SRC-101 preserves reviewed-witness safeguards and complete provisional sequential reconstruction while 1979/1981 publication comparison remains pending','all ten witness-only Theologico-Political sources preserve registered-witness, pending-study, edition-comparison, noncertification, and no-successor safeguards'])
    t=d['termination']; t['theologico_political_independent_study_state']='INCOMPLETE_9_OF_19'; t['next_required_units']=['conduct independent sequential reconstruction of CORPUS-SRC-104 from CORPUS-WIT-104','compare the reviewed 1997 CORPUS-WIT-101 item with the 1979 and 1981 publication states when available','conduct independent sequential reconstruction for the remaining ten writings','expand independent biblical, Greek, Jewish, Christian, Spinozist, medieval, modern, and reviewed-work witnesses']; dump(p,d)

def findings():
    p='findings/index.yaml'; d=load(p); d['identity']['version']='1.9.0'; d['revision_history']={'predecessor_version':'1.8.0','predecessor_blob_sha':'PRESERVED_BY_GIT','transformation':'SUBSTANTIVE_FORWARD_REVISION','reason':'Register PROGRESS-RETURN-STUDY-001 as FINDSET-016 and jurisdiction-preserving syntheses FINDSET-131 through FINDSET-133 while preserving publication-state, noncorroboration, noncertification, and no-successor safeguards.'}
    adds=[{'finding_set_id':'FINDSET-016','path':SPATH,'record_class':'SOURCE_SPECIFIC_STUDY','record_role':'SOURCE_SPECIFIC_SEQUENTIAL_RECONSTRUCTION','source_bindings':[SRC],'problem_bindings':['theologico-political','athens-vs-jerusalem','ancients-vs-moderns'],'status':'COMPLETE_PROVISIONAL_FOR_REVIEWED_1997_COLLECTED_WITNESS','certification':'NOT_CERTIFIED','derived_local_syntheses':['FINDSET-131','FINDSET-132','FINDSET-133'],'witness_id':WIT,'earlier_publication_comparison':'PENDING','independent_corroboration':'INCOMPLETE','successor_effect':'NONE'},{'finding_set_id':'FINDSET-131','path':TP,'record_class':'PROBLEM_LOCAL_SYNTHESIS','record_role':'SOURCE_TO_PROBLEM_SYNTHESIS','source_bindings':[SRC],'problem_bindings':['theologico-political'],'adjacent_problem_references':['athens-vs-jerusalem','ancients-vs-moderns'],'derived_from':['FINDSET-016'],'status':'PROVISIONAL_NOT_CERTIFIED','certification':'NOT_CERTIFIED','successor_effect':'NONE'},{'finding_set_id':'FINDSET-132','path':AVJ,'record_class':'PROBLEM_LOCAL_SYNTHESIS','record_role':'SOURCE_TO_PROBLEM_SYNTHESIS','source_bindings':[SRC],'problem_bindings':['athens-vs-jerusalem'],'theologico_political_reference':'theologico-political','derived_from':['FINDSET-016'],'status':'PROVISIONAL_NOT_CERTIFIED','certification':'NOT_CERTIFIED','successor_effect':'NONE'},{'finding_set_id':'FINDSET-133','path':AVM,'record_class':'PROBLEM_LOCAL_SYNTHESIS','record_role':'SOURCE_TO_PROBLEM_SYNTHESIS','source_bindings':[SRC],'problem_bindings':['ancients-vs-moderns'],'theologico_political_reference':'theologico-political','derived_from':['FINDSET-016'],'status':'PROVISIONAL_NOT_CERTIFIED','certification':'NOT_CERTIFIED','successor_effect':'NONE'}]
    ids={x['finding_set_id'] for x in d['finding_sets']}
    for it in adds:
        if it['finding_set_id'] in ids:continue
        pos=next(i for i,x in enumerate(d['finding_sets']) if int(x['finding_set_id'].split('-')[1]) >= (100 if it['record_class']=='SOURCE_SPECIFIC_STUDY' else 200)); d['finding_sets'].insert(pos,it); ids.add(it['finding_set_id'])
    probs=['nomos-vs-physis','philosophy-vs-poetry','theory-vs-practice','theologico-political','athens-vs-jerusalem','wise-vs-vulgar','ancients-vs-moderns']; byp={x:[] for x in probs}; classes={'SOURCE_SPECIFIC_STUDY':[],'INTEGRATION_GOVERNANCE_RECORD':[],'PROBLEM_LOCAL_SYNTHESIS':[],'MIGRATION_TRANSACTION_LEDGER':[],'PRESERVED_FINDING_BASIS':[]}; direct=['CORPUS-SRC-001','CORPUS-SRC-002','CORPUS-SRC-003','CORPUS-SRC-101','CORPUS-SRC-102','CORPUS-SRC-103','CORPUS-SRC-105','CORPUS-SRC-108','CORPUS-SRC-111','CORPUS-SRC-113','CORPUS-SRC-116']; bys={x:[] for x in direct}; bys['CORPUS-SRC-101-119']=[]; pred={f'CORPUS-SRC-{i:03d}' for i in range(101,120)}; sep=set(direct)&pred
    for it in d['finding_sets']:
        fid=it['finding_set_id']; [byp[p].append(fid) for p in it.get('problem_bindings',[]) if p in byp]; rc=it.get('record_class');
        if rc in {'ACTIVE_PREDECESSOR_FINDING_BASIS','ACCEPTED_MIGRATION_SOURCE_FINDING_BASIS'}:classes['PRESERVED_FINDING_BASIS'].append(fid)
        elif rc in classes:classes[rc].append(fid)
        binds=set(it.get('source_bindings',[])); [bys[s].append(fid) for s in direct if s in binds]
        if binds&pred and not (len(binds)==1 and next(iter(binds)) in sep):bys['CORPUS-SRC-101-119'].append(fid)
    d['indexes']={'by_problem':byp,'by_source':bys,'by_record_class':classes}; d['coverage'].update({'finding_sets_registered':54,'source_specific_and_integration_records_registered':16,'problem_syntheses_registered':33,'current_problem_synthesis_tree_yaml_records_accounted_for':33,'corpus_study_records_accounted_for':16}); next(x for x in d['findings_gaps'] if x['gap_id']=='FINDINGS-GAP-003')['statement']='Nine of the nineteen Theologico-Political writings now have complete provisional item studies; the remaining ten lack individual sequential studies.'; d['validation_rules']=uniq([x for x in d['validation_rules'] if not x.startswith('FINDSET-016 must')]+['FINDSET-016 must derive only FINDSET-131 through FINDSET-133, preserve CORPUS-WIT-101, pending earlier-publication comparison, noncorroboration, and no-successor safeguards']); dump(p,d)

def metadata():
    p='manifest.yaml'; d=load(p); d['identity']['version']='1.13.0'; d['revision_history']={'predecessor_version':'1.12.0','predecessor_blob_sha':'PRESERVED_BY_GIT','reason':'Register PROGRESS-RETURN-STUDY-001 as the ninth complete provisional Theologico-Political item study and synchronize corpus v1.17.0, findings v1.9.0, audit v3.1.0, mapping v1.13.0, process v1.15.0, and schedule v1.13.0 while preserving ten pending studies, publication-state limits, noncertification, predecessor authority, and the Sanctum repin block.'}; d['audit']['version']='3.1.0'; d['component_completion']['theologico_political_item_level_source_statuses']='19_OF_19_IDENTITIES_19_OF_19_REVIEWED_ITEM_WITNESSES_9_OF_19_COMPLETE_PROVISIONAL_ITEM_STUDIES'; d['corpus']['registry_version']='1.17.0'; s=d['corpus']['theologico_political_item_level_statuses']; s['independent_sequential_study_count']=9; s['remaining_without_independent_sequential_study']=10; s['completed_study_ids']=uniq(s.get('completed_study_ids',[])+[STUDY]); d['findings']['registry_version']='1.9.0'; d['findings']['newly_registered']=['FINDSET-016','FINDSET-131','FINDSET-132','FINDSET-133']; dump(p,d)
    p='history/production-plans/2026-07-27-theologico-political-reviewed-witness-priority.yaml'; d=load(p); d['identity']['version']='1.13.0'; d['status']['independent_sequential_study_completion']='INCOMPLETE_9_OF_19'; item=next(x for g in d['priority_groups'] for x in g['items'] if x['source_id']==SRC); item['study_id']=STUDY; item['state']='REVIEWED_WITNESS_AND_COMPLETE_PROVISIONAL_SEQUENTIAL_STUDY'; item['next_action']='COMPARE_1979_1981_PUBLICATION_STATES_AND_EXPAND_INDEPENDENT_WITNESSES'; d['selection']['completed_study_ids']=uniq(d['selection'].get('completed_study_ids',[])+[STUDY]); d['termination']['independent_sequential_reconstruction']='INCOMPLETE_9_OF_19'; d['termination']['next_item_study']='CORPUS-SRC-104'; d['next_item_study_unit']={'source_id':'CORPUS-SRC-104','title':'Preface to Isaac Husik, Philosophical Essays','action':'INDEPENDENT_SEQUENTIAL_RECONSTRUCTION_FROM_REGISTERED_WITNESS','prerequisite':'SATISFIED_CORPUS_WIT_104_REGISTERED','following_source':'CORPUS-SRC-106'}; dump(p,d)
    p='history/production-plans/2026-07-27-ten-step-completion-process.yaml'; d=load(p); d['identity']['version']='1.15.0';
    for st in d['steps']:
        if st['sequence']==1:st['current_version']='3.1.0'
        if st['sequence']==2:st['current_version']='1.13.0'
        if st['sequence']==8:st['completed']=uniq(st.get('completed',[])+['PROGRESS-RETURN-STUDY-001 is complete provisional for CORPUS-WIT-101']); rem=st.get('remaining',[]); st['remaining']=['conduct ten independent sequential item studies, beginning with CORPUS-SRC-104']+rem[1:]
    d['current_production_unit']={'step':8,'completed_subunit':{'title':'Progress or Return? independent sequential reconstruction','state':'COMPLETE_PROVISIONAL_PENDING_BRANCH_VALIDATION_AND_MERGE','source_id':SRC,'witness_id':WIT,'study_id':STUDY,'study_coverage':'INCOMPLETE_9_OF_19'},'next_subunit':{'title':'Preface to Isaac Husik, Philosophical Essays independent sequential reconstruction','source_id':'CORPUS-SRC-104','witness_id':'CORPUS-WIT-104','following_source':'CORPUS-SRC-106'}}; dump(p,d)
    p='migrations/lean-operational-interface.yaml'; d=load(p); d['identity']['version']='1.13.0'; d['completion_audit']['version']='3.1.0'; d['production_process']['completed_study_subunit']='NINE_OF_19_COMPLETE_PROVISIONAL_TEN_PENDING'; c=d['mappings']['corpus']; c['interface']['registry_version']='1.17.0'; s=c['theologico_political_item_level_statuses']; s['independent_sequential_study_count']=9; s['remaining_without_independent_sequential_study']=10; s['completed_study_ids']=uniq(s.get('completed_study_ids',[])+[STUDY]); s['witness_only_source_ids']=[x for x in s.get('witness_only_source_ids',[]) if x!=SRC]; f=d['mappings']['findings']; f['interface']['registry_version']='1.9.0'; f['newly_registered']=[{'finding_set_id':'FINDSET-016','path':SPATH},{'finding_set_id':'FINDSET-131','path':TP,'derived_from':'FINDSET-016'},{'finding_set_id':'FINDSET-132','path':AVJ,'derived_from':'FINDSET-016'},{'finding_set_id':'FINDSET-133','path':AVM,'derived_from':'FINDSET-016'}]; dump(p,d)
    p='audits/operational-completeness.yaml'; d=load(p); d['identity']['version']='3.1.0'; d['basis']['current_revision_scope']='production/corpus-src-101-sequential-reconstruction'; s=d['summary']['theologico_political_item_level_status']; s['independently_reconstructed_count_within_this_sequence']=9; s['remaining_without_independent_sequential_study']=10; s['completed_source_ids']=uniq(s.get('completed_source_ids',[])+[SRC]); s['completed_witness_ids']=uniq(s.get('completed_witness_ids',[])+[WIT]); s['completed_study_ids']=uniq(s.get('completed_study_ids',[])+[STUDY]); s['witness_only_source_ids']=[x for x in uniq(s.get('witness_only_source_ids',[])) if x!=SRC]; s['witness_only_witness_ids']=[x for x in uniq(s.get('witness_only_witness_ids',[])) if x!=WIT]; d['summary']['completed_operational_units']=uniq(d['summary'].get('completed_operational_units',[])+['PROGRESS-RETURN-STUDY-001 complete provisional sequential reconstruction','CORPUS-STUDY-016 and FINDSET-016 typed registrations','FINDSET-131 through FINDSET-133 jurisdiction-preserving problem-local syntheses']); d['summary']['remaining_major_deficiencies']=['ten Theologico-Political writings still require independent sequential item studies']+[x for x in uniq(d['summary'].get('remaining_major_deficiencies',[])) if not re.match(r'^(ten|eleven|twelve|thirteen|fourteen|fifteen) Theologico-Political writings',x)]; dump(p,d)

def code_tests():
    p=ROOT/'corpus_registry.py'; text=p.read_text(encoding='utf-8'); reg=load('corpus/index.yaml'); ws={x['source_id']:x for x in reg['reviewed_witnesses']}; # derive complete specs from registry/source statuses
    complete={}
    for sid in [f'CORPUS-SRC-{i:03d}' for i in [101,102,103,105,108,109,111,113,116]]:
        src=next(x for x in reg['source_entities'] if x['source_id']==sid); study_id=src['study_records'][0]; stentry=next(x for x in reg['study_records'] if x['study_id']==study_id); st=load(stentry['path']); status=load(next(x for x in reg['source_status_records'] if x['source_id']==sid)['path']); w=ws[sid]; spec={'status_id':sid.replace('CORPUS-SRC','CORPUS-STATUS'),'witness_id':w['witness_id'],'study_id':study_id,'internal_study_id':status['status']['independent_sequential_study'],'study_path':stentry['path'],'witness_record_path':w.get('witness_record_path'),'printed_page_range':w['printed_page_range'],'pdf_page_range_one_based':w['pdf_page_range_one_based'],'reading_state':st['termination']['reading_state'],'platform_reference':w.get('witness_class')=='PLATFORM_REFERENCE_WITNESS'}
        if spec['platform_reference']:spec['platform_object_identifier']=w['platform_object_identifier']
        complete[sid]=spec
    wonly={}
    for i in range(101,120):
        sid=f'CORPUS-SRC-{i:03d}'
        if sid in complete:continue
        w=ws[sid]; wonly[sid]={'status_id':f'CORPUS-STATUS-{i:03d}','witness_id':f'CORPUS-WIT-{i:03d}','witness_record_path':w['witness_record_path'],'printed_page_range':w['printed_page_range'],'pdf_page_range_one_based':w['pdf_page_range_one_based'],'container_sha256':w['container_sha256'],'container_file_size_bytes':w['container_file_size_bytes'],'container_page_count':w['container_page_count']}
    region='COMPLETE_TP_ITEMS: dict[str, dict[str, Any]] = '+pformat(complete,width=110,sort_dicts=False)+'\n\nWITNESS_ONLY_TP_ITEMS: dict[str, dict[str, Any]] = '+pformat(wonly,width=110,sort_dicts=False)+'\n\n\n'; text,n=re.subn(r'COMPLETE_TP_ITEMS: dict\[str, dict\[str, Any\]\] = \{.*?\n\nclass CorpusRegistryError',region+'class CorpusRegistryError',text,count=1,flags=re.S); assert n==1; text=text.replace('identity.get("version") != "1.16.0"','identity.get("version") != "1.17.0"').replace('identity.version must be 1.16.0','identity.version must be 1.17.0').replace('"study records": (len(study_ids), 15)','"study records": (len(study_ids), 16)').replace('"theologico_political_independent_item_studies_registered": 8','"theologico_political_independent_item_studies_registered": 9').replace('!= "INCOMPLETE_8_OF_19"','!= "INCOMPLETE_9_OF_19"').replace('must be INCOMPLETE_8_OF_19','must be INCOMPLETE_9_OF_19'); p.write_text(text,encoding='utf-8')
    p=ROOT/'findings_registry.py'; text=p.read_text(encoding='utf-8'); synth=sorted(str(x.relative_to(ROOT)) for x in (ROOT/'problems').glob('*/synthesis/*.yaml') if x.is_file()); stxt='EXPECTED_SYNTHESIS_PATHS = {\n'+''.join(f'    "{x}",\n' for x in synth)+'}\n\n'; text,n=re.subn(r'EXPECTED_SYNTHESIS_PATHS = \{.*?\n\}\n\n',stxt,text,count=1,flags=re.S); assert n==1; text=text.replace('    "CORPUS-SRC-003",\n','    "CORPUS-SRC-003",\n    "CORPUS-SRC-101",\n',1); text=text.replace('separately_indexed = {','separately_indexed = {"CORPUS-SRC-101", ',1) if '"CORPUS-SRC-101"' not in text[text.find('separately_indexed'):text.find('separately_indexed')+300] else text; contract='''    "FINDSET-016": {\n        "source_id": "CORPUS-SRC-101",\n        "local_syntheses": ["FINDSET-131", "FINDSET-132", "FINDSET-133"],\n        "problem_bindings": {"FINDSET-131": "theologico-political", "FINDSET-132": "athens-vs-jerusalem", "FINDSET-133": "ancients-vs-moderns"},\n        "required_limits": {"witness_id": "CORPUS-WIT-101", "earlier_publication_comparison": "PENDING", "independent_corroboration": "INCOMPLETE"},\n    },\n''';
    if '"FINDSET-016": {' not in text:text=text.replace('\n}\n\n\nclass FindingsRegistryError','\n'+contract+'}\n\n\nclass FindingsRegistryError',1)
    text=text.replace('identity.get("version") != "1.8.0"','identity.get("version") != "1.9.0"').replace('identity.version must be 1.8.0','identity.version must be 1.9.0').replace('if len(finding_ids) != 50:','if len(finding_ids) != 54:').replace('expected 50 finding sets','expected 54 finding sets'); p.write_text(text,encoding='utf-8')
    reps={"tests/test_corpus_registry.py":{"1.16.0":"1.17.0","55,":"56,",'study_records_registered"], 15':'study_records_registered"], 16',"test_eleven_tp_sources_have_witnesses_but_still_require_study":"test_ten_tp_sources_have_witnesses_but_still_require_study","self.assertEqual(len(sources), 11)":"self.assertEqual(len(sources), 10)"},"tests/test_findings_registry.py":{"1.8.0":"1.9.0","len(finding_ids), 50":"len(finding_ids), 54","len(registered), 30":"len(registered), 33","len(registered), 15":"len(registered), 16"},"tests/test_interface_consistency.py":{"eight_study":"nine_study",'study_count"], 8':'study_count"], 9','sequence"], 8':'sequence"], 9','study"], 8':'study"], 9','study"], 11':'study"], 10',"INCOMPLETE_8_OF_19":"INCOMPLETE_9_OF_19",'next_item_study"], "CORPUS-SRC-101"':'next_item_study"], "CORPUS-SRC-104"','"HOBBES-PREFACE-STUDY-001"]':'"HOBBES-PREFACE-STUDY-001", "PROGRESS-RETURN-STUDY-001"]'},"tests/test_pr21_talmon_completion.py":{"1.12.0":"1.13.0","3.0.0":"3.1.0","1.14.0":"1.15.0","1.16.0":"1.17.0","1.8.0":"1.9.0",'study_count"], 8':'study_count"], 9','study"], 11':'study"], 10','next_item_study"], "CORPUS-SRC-101"':'next_item_study"], "CORPUS-SRC-104"','"HOBBES-PREFACE-STUDY-001"]':'"HOBBES-PREFACE-STUDY-001", "PROGRESS-RETURN-STUDY-001"]'},"tests/test_tp_witness_coverage_complete.py":{"INCOMPLETE_8_OF_19":"INCOMPLETE_9_OF_19",'theologico_political_independent_item_studies_registered"], 8':'theologico_political_independent_item_studies_registered"], 9',"test_eleven_witness_only_items_remain_noncertified_and_unstudied":"test_ten_witness_only_items_remain_noncertified_and_unstudied","self.assertEqual(len(witness_only), 11)":"self.assertEqual(len(witness_only), 10)", '"CORPUS-SRC-116"}':'"CORPUS-SRC-116", "CORPUS-SRC-101"}'},"tests/test_corpus_wit_102_platform_registration.py":{"INCOMPLETE_8_OF_19":"INCOMPLETE_9_OF_19"}}
    for path,rr in reps.items():
        pp=ROOT/path; tt=pp.read_text(encoding='utf-8')
        for a,b in rr.items():tt=tt.replace(a,b)
        pp.write_text(tt,encoding='utf-8')
    pp=ROOT/'tests/test_interface_consistency.py'; tt=pp.read_text(encoding='utf-8');
    if '"FINDSET-016":' not in tt:tt=tt.replace('"FINDSET-015": [("FINDSET-129", "theologico-political"), ("FINDSET-130", "ancients-vs-moderns")],','"FINDSET-015": [("FINDSET-129", "theologico-political"), ("FINDSET-130", "ancients-vs-moderns")],\n            "FINDSET-016": [("FINDSET-131", "theologico-political"), ("FINDSET-132", "athens-vs-jerusalem"), ("FINDSET-133", "ancients-vs-moderns")],')
    pp.write_text(tt,encoding='utf-8')

def main():corpus();findings();metadata();code_tests();print('Materialized CORPUS-SRC-101 study integration.')
if __name__=='__main__':main()
