#!/usr/bin/env python3
from __future__ import annotations

from pathlib import Path
from pprint import pformat
import re
import yaml

ROOT = Path(__file__).resolve().parents[1]
SRC="CORPUS-SRC-116"; WIT="CORPUS-WIT-116"; STUDY="HOBBES-PREFACE-STUDY-001"; CORPUS_STUDY="CORPUS-STUDY-015"
STUDY_PATH="studies/theologico-political/preface-to-hobbes-politische-wissenschaft/sequential-reconstruction.yaml"
TP_SYN="problems/theologico-political/synthesis/preface-to-hobbes-politische-wissenschaft.yaml"
AVM_SYN="problems/ancients-vs-moderns/synthesis/preface-to-hobbes-politische-wissenschaft.yaml"

def load(path):
    with (ROOT/path).open(encoding="utf-8") as f: return yaml.safe_load(f)
def dump(path,data): (ROOT/path).write_text(yaml.safe_dump(data,sort_keys=False,allow_unicode=True,width=110),encoding="utf-8")
def uniq(xs):
    out=[]
    for x in xs:
        if x not in out: out.append(x)
    return out

def corpus():
    p="corpus/index.yaml"; d=load(p); d["identity"]["version"]="1.16.0"
    d["revision_history"]={"predecessor_version":"1.15.0","predecessor_blob_sha":"5104e4b0a1b3ac55d5df057a365d52ce3c785426","transformation":"SUBSTANTIVE_FORWARD_REVISION","reason":"Register HOBBES-PREFACE-STUDY-001 as the eighth complete provisional Theologico-Political item study while preserving the reviewed item's documentary omission, pending 1965/1979-80 comparison, noncorroboration, noncertification, predecessor authority, and no successor effect."}
    s=next(x for x in d["source_entities"] if x["source_id"]==SRC); s["study_records"]=[CORPUS_STUDY]; s["item_level_source_status"]="REVIEWED_ITEM_WITNESS_REGISTERED_AND_COMPLETE_PROVISIONAL_SEQUENTIAL_RECONSTRUCTION"; s["study_status"]="COMPLETE_PROVISIONAL_FOR_REVIEWED_1997_COLLECTED_WITNESS_WITH_DOCUMENTARY_OMISSION_LIMIT"; s["limits"]=["reviewed witness reproduces the Maletz English translation in the 1997 collection, not separately reviewed 1965 German or 1979-80 English textual states","printed pages 453-456 correspond to one-based PDF pages 472-475","Strauss's reproduced preface body ends on printed page 454 and the final three paragraphs identified by editorial note 8 are omitted from the reviewed body","HOBBES-PREFACE-STUDY-001 is source-local and not independent corroboration of Hobbes, Spinoza, or named interlocutors","the sovereign-peace predecessor formulation remains only partially retested because the required omitted paragraphs were not reviewed"]
    e=next(x for x in d["source_status_records"] if x["source_id"]==SRC); e["completion"]="REVIEWED_ITEM_WITNESS_REGISTERED_AND_COMPLETE_PROVISIONAL_SEQUENTIAL_RECONSTRUCTION"
    if not any(x.get("study_id")==CORPUS_STUDY for x in d["study_records"]): d["study_records"].append({"study_id":CORPUS_STUDY,"source_id":SRC,"path":STUDY_PATH,"record_role":"SOURCE_SPECIFIC_SEQUENTIAL_RECONSTRUCTION","completion":"COMPLETE_PROVISIONAL_FOR_REVIEWED_1997_COLLECTED_WITNESS_WITH_DOCUMENTARY_OMISSION_LIMIT","certification":"NOT_CERTIFIED"})
    c=d["coverage"]; c["study_records_registered"]=15; c["theologico_political_independent_item_studies_registered"]=8; c["current_studies_tree_yaml_records_accounted_for"]=55
    gap=next(x for x in d["corpus_gaps"] if x["gap_id"]=="CORPUS-GAP-003"); gap["statement"]="All nineteen predecessor writings have bounded source identities and reviewed item witnesses; eight have complete provisional sequential studies, while the remaining eleven lack independent item studies."
    d["validation_rules"]=uniq([x for x in d["validation_rules"] if "witness-only Theologico-Political sources" not in x]+["CORPUS-SRC-116 preserves the documentary-omission limit while recording complete provisional reconstruction of the text actually present in CORPUS-WIT-116","all eleven witness-only Theologico-Political sources preserve registered-witness, pending-study, edition-comparison, noncertification, and no-successor safeguards"])
    t=d["termination"]; t["theologico_political_independent_study_state"]="INCOMPLETE_8_OF_19"; t["next_required_units"]=["conduct independent sequential reconstruction of CORPUS-SRC-101 from CORPUS-WIT-101","review the omitted final three paragraphs and compare the 1965 German and 1979-80 English Hobbes-preface textual states when lawful witnesses are available","conduct independent sequential reconstruction for the remaining eleven writings","expand independent Hobbesian, Spinozist, biblical, Greek, medieval, modern, and reviewed-work witnesses"]
    dump(p,d)

def findings():
    p="findings/index.yaml"; d=load(p); d["identity"]["version"]="1.8.0"; d["revision_history"]={"predecessor_version":"1.7.0","predecessor_blob_sha":"PRESERVED_BY_GIT","transformation":"SUBSTANTIVE_FORWARD_REVISION","reason":"Register HOBBES-PREFACE-STUDY-001 as FINDSET-015 and its jurisdiction-preserving Theologico-Political and Ancients-versus-Moderns syntheses as FINDSET-129 and FINDSET-130 while preserving the documentary-omission, textual-state, noncorroboration, noncertification, and no-successor safeguards."}
    adds=[{"finding_set_id":"FINDSET-015","path":STUDY_PATH,"record_class":"SOURCE_SPECIFIC_STUDY","record_role":"SOURCE_SPECIFIC_SEQUENTIAL_RECONSTRUCTION","source_bindings":[SRC],"problem_bindings":["theologico-political","ancients-vs-moderns"],"status":"COMPLETE_PROVISIONAL_WITH_DOCUMENTARY_OMISSION_LIMIT","certification":"NOT_CERTIFIED","derived_local_syntheses":["FINDSET-129","FINDSET-130"],"witness_id":WIT,"original_1965_german_preface_comparison":"PENDING","interpretation_1979_80_translation_comparison":"PENDING","omitted_text_review":"INCOMPLETE","independent_corroboration":"INCOMPLETE","successor_effect":"NONE"},{"finding_set_id":"FINDSET-129","path":TP_SYN,"record_class":"PROBLEM_LOCAL_SYNTHESIS","record_role":"SOURCE_TO_PROBLEM_SYNTHESIS","source_bindings":[SRC],"problem_bindings":["theologico-political"],"adjacent_problem_reference":"ancients-vs-moderns","derived_from":["FINDSET-015"],"status":"PROVISIONAL_WITH_DOCUMENTARY_LIMIT_NOT_CERTIFIED","certification":"NOT_CERTIFIED","successor_effect":"NONE"},{"finding_set_id":"FINDSET-130","path":AVM_SYN,"record_class":"PROBLEM_LOCAL_SYNTHESIS","record_role":"SOURCE_TO_PROBLEM_SYNTHESIS","source_bindings":[SRC],"problem_bindings":["ancients-vs-moderns"],"theologico_political_reference":"theologico-political","derived_from":["FINDSET-015"],"status":"PROVISIONAL_NOT_CERTIFIED","certification":"NOT_CERTIFIED","successor_effect":"NONE"}]
    existing={x["finding_set_id"] for x in d["finding_sets"]}
    for item in adds:
        if item["finding_set_id"] in existing: continue
        pos=next(i for i,x in enumerate(d["finding_sets"]) if int(x["finding_set_id"].split("-")[1]) >= (100 if item["record_class"]=="SOURCE_SPECIFIC_STUDY" else 200)); d["finding_sets"].insert(pos,item); existing.add(item["finding_set_id"])
    problems=["nomos-vs-physis","philosophy-vs-poetry","theory-vs-practice","theologico-political","athens-vs-jerusalem","wise-vs-vulgar","ancients-vs-moderns"]; byp={x:[] for x in problems}; classes={"SOURCE_SPECIFIC_STUDY":[],"INTEGRATION_GOVERNANCE_RECORD":[],"PROBLEM_LOCAL_SYNTHESIS":[],"MIGRATION_TRANSACTION_LEDGER":[],"PRESERVED_FINDING_BASIS":[]}; direct=["CORPUS-SRC-001","CORPUS-SRC-002","CORPUS-SRC-003","CORPUS-SRC-102","CORPUS-SRC-103","CORPUS-SRC-105","CORPUS-SRC-108","CORPUS-SRC-111","CORPUS-SRC-113","CORPUS-SRC-116"]; bys={x:[] for x in direct}; bys["CORPUS-SRC-101-119"]=[]; pred={f"CORPUS-SRC-{i:03d}" for i in range(101,120)}; separate=set(direct)&pred
    for item in d["finding_sets"]:
        fid=item["finding_set_id"]
        for pr in item.get("problem_bindings",[]):
            if pr in byp: byp[pr].append(fid)
        rc=item.get("record_class");
        if rc in {"ACTIVE_PREDECESSOR_FINDING_BASIS","ACCEPTED_MIGRATION_SOURCE_FINDING_BASIS"}: classes["PRESERVED_FINDING_BASIS"].append(fid)
        elif rc in classes: classes[rc].append(fid)
        binds=set(item.get("source_bindings",[]))
        for sid in direct:
            if sid in binds: bys[sid].append(fid)
        if binds & pred and not (len(binds)==1 and next(iter(binds)) in separate): bys["CORPUS-SRC-101-119"].append(fid)
    d["indexes"]={"by_problem":byp,"by_source":bys,"by_record_class":classes}; d["coverage"].update({"finding_sets_registered":50,"source_specific_and_integration_records_registered":15,"problem_syntheses_registered":30,"current_problem_synthesis_tree_yaml_records_accounted_for":30,"corpus_study_records_accounted_for":15}); next(x for x in d["findings_gaps"] if x["gap_id"]=="FINDINGS-GAP-003")["statement"]="Eight of the nineteen Theologico-Political writings now have complete provisional item studies; the remaining eleven lack individual sequential studies."; d["validation_rules"]=uniq([x for x in d["validation_rules"] if not x.startswith("FINDSET-015 must")]+["FINDSET-015 must derive only FINDSET-129 and FINDSET-130, preserve CORPUS-WIT-116, the omitted-text limit, pending 1965/1979-80 comparison, noncorroboration, and no-successor safeguards"]); dump(p,d)

def other():
    p="manifest.yaml"; d=load(p); d["identity"]["version"]="1.12.0"; d["revision_history"]={"predecessor_version":"1.11.0","predecessor_blob_sha":"PRESERVED_BY_GIT","reason":"Register HOBBES-PREFACE-STUDY-001 as the eighth complete provisional Theologico-Political item study and synchronize corpus v1.16.0, findings v1.8.0, audit v3.0.0, mapping v1.12.0, process v1.14.0, and schedule v1.12.0 while preserving eleven pending studies, the documentary-omission limit, noncertification, predecessor authority, and the Sanctum repin block."}; d["audit"]["version"]="3.0.0"; d["component_completion"]["theologico_political_item_level_source_statuses"]="19_OF_19_IDENTITIES_19_OF_19_REVIEWED_ITEM_WITNESSES_8_OF_19_COMPLETE_PROVISIONAL_ITEM_STUDIES"; d["corpus"]["registry_version"]="1.16.0"; s=d["corpus"]["theologico_political_item_level_statuses"]; s["independent_sequential_study_count"]=8; s["remaining_without_independent_sequential_study"]=11; s["completed_study_ids"]=uniq(s.get("completed_study_ids",[])+[STUDY]); s["rule"]="All nineteen predecessor items have reviewed witnesses and eight have complete provisional source studies. Witness and study completion remain distinct from independent corroboration, doctrinal certification, migration completion, successor activation, or repository completion."; d["corpus"]["limitation"]="All nineteen predecessor writings have bounded identities and reviewed item witnesses. Eight have complete provisional sequential studies; CORPUS-SRC-116 retains an explicit documentary-omission limit, and eleven sources still lack independent studies. Textual-state comparisons, independent witnesses, and source-text access remain incomplete."; d["findings"]["registry_version"]="1.8.0"; d["findings"]["newly_registered"]=["FINDSET-015","FINDSET-129","FINDSET-130"]; dump(p,d)
    p="history/production-plans/2026-07-27-theologico-political-reviewed-witness-priority.yaml"; d=load(p); d["identity"]["version"]="1.12.0"; d["revision_history"]={"predecessor_version":"1.11.0","predecessor_blob_sha":"PRESERVED_BY_GIT","reason":"Complete HOBBES-PREFACE-STUDY-001 from CORPUS-WIT-116, advancing independent sequential study coverage to 8-of-19 and the next study unit to CORPUS-SRC-101 while preserving complete witness coverage and the documentary-omission limit."}; d["status"]["independent_sequential_study_completion"]="INCOMPLETE_8_OF_19"; item=next(x for g in d["priority_groups"] for x in g["items"] if x["source_id"]==SRC); item["study_id"]=STUDY; item["state"]="REVIEWED_WITNESS_AND_COMPLETE_PROVISIONAL_SEQUENTIAL_STUDY_WITH_DOCUMENTARY_OMISSION_LIMIT"; item["next_action"]="REVIEW_OMITTED_PARAGRAPHS_AND_COMPARE_1965_1979_80_TEXTUAL_STATES"; d["selection"]["completed_study_ids"]=uniq(d["selection"].get("completed_study_ids",[])+[STUDY]); d["selection"]["selection_state"]="NINETEEN_REVIEWED_ITEM_WITNESSES_EIGHT_COMPLETE_PROVISIONAL_SEQUENTIAL_STUDIES"; d["termination"]["independent_sequential_reconstruction"]="INCOMPLETE_8_OF_19"; d["termination"]["next_item_study"]="CORPUS-SRC-101"; d["next_item_study_unit"]={"source_id":"CORPUS-SRC-101","title":"Progress or Return?","action":"INDEPENDENT_SEQUENTIAL_RECONSTRUCTION_FROM_REGISTERED_WITNESS","prerequisite":"SATISFIED_CORPUS_WIT_101_REGISTERED","following_source":"CORPUS-SRC-104"}; dump(p,d)
    p="history/production-plans/2026-07-27-ten-step-completion-process.yaml"; d=load(p); d["identity"]["version"]="1.14.0"; d["revision_history"]={"predecessor_version":"1.13.0","predecessor_blob_sha":"PRESERVED_BY_GIT","reason":"Complete HOBBES-PREFACE-STUDY-001 as the eighth provisional Theologico-Political sequential reconstruction and advance the next study unit to CORPUS-SRC-101 while preserving the documentary-omission limit and eleven remaining studies."};
    for st in d["steps"]:
        if st["sequence"]==1: st["current_version"]="3.0.0"
        if st["sequence"]==2: st["current_version"]="1.12.0"
        if st["sequence"]==7: st["completed"]=uniq(st.get("completed",[])+["Preface to Hobbes Politische Wissenschaft supplies distinct provisional syntheses to Theologico-Political and Ancients-versus-Moderns with a documentary-omission limit"])
        if st["sequence"]==8: st["completed"]=uniq(st.get("completed",[])+["HOBBES-PREFACE-STUDY-001 is complete provisional for the text present in CORPUS-WIT-116"]); rem=st.get("remaining",[]); st["remaining"]=["conduct eleven independent sequential item studies, beginning with CORPUS-SRC-101"]+rem[1:]
    d["current_production_unit"]={"step":8,"completed_subunit":{"title":"Preface to Hobbes Politische Wissenschaft independent sequential reconstruction","state":"COMPLETE_PROVISIONAL_PENDING_BRANCH_VALIDATION_AND_MERGE","source_id":SRC,"witness_id":WIT,"study_id":STUDY,"witness_coverage":"COMPLETE_19_OF_19","study_coverage":"INCOMPLETE_8_OF_19","documentary_omission_limit":"ACTIVE","non_effect":"Source-study completion does not supply independent corroboration, doctrine, certified migration, successor activation, predecessor displacement, or completed-interface readiness."},"next_subunit":{"title":"Progress or Return? independent sequential reconstruction","source_id":"CORPUS-SRC-101","witness_id":"CORPUS-WIT-101","following_source":"CORPUS-SRC-104"}}; dump(p,d)
    p="migrations/lean-operational-interface.yaml"; d=load(p); d["identity"]["version"]="1.12.0"; d["revision_history"]={"predecessor_version":"1.11.0","predecessor_blob_sha":"PRESERVED_BY_GIT","reason":"Synchronize HOBBES-PREFACE-STUDY-001, corpus v1.16.0, findings v1.8.0, audit v3.0.0, process v1.14.0, and schedule v1.12.0 while preserving eleven pending studies and the documentary-omission limit."}; d["completion_audit"]["version"]="3.0.0"; d["production_process"]["completed_study_subunit"]="EIGHT_OF_19_COMPLETE_PROVISIONAL_ELEVEN_PENDING"; c=d["mappings"]["corpus"]; c["interface"]["registry_version"]="1.16.0"; s=c["theologico_political_item_level_statuses"]; s["independent_sequential_study_count"]=8; s["remaining_without_independent_sequential_study"]=11; s["completed_study_ids"]=uniq(s.get("completed_study_ids",[])+[STUDY]); s["witness_only_source_ids"]=[x for x in s.get("witness_only_source_ids",[]) if x!=SRC]; c["limit"]="Current-state exhaustiveness, nineteen reviewed item witnesses, and eight complete provisional item studies do not create a complete corpus, supply independent corroboration, resolve documentary omissions, certify findings, or authorize migration and activation."; f=d["mappings"]["findings"]; f["interface"]["registry_version"]="1.8.0"; f["newly_registered"]=[{"finding_set_id":"FINDSET-015","path":STUDY_PATH},{"finding_set_id":"FINDSET-129","path":TP_SYN,"derived_from":"FINDSET-015"},{"finding_set_id":"FINDSET-130","path":AVM_SYN,"derived_from":"FINDSET-015"}]; dump(p,d)
    p="audits/operational-completeness.yaml"; d=load(p); d["identity"]["version"]="3.0.0"; d["revision_history"]={"predecessor_version":"2.9.0","predecessor_blob_sha":"PRESERVED_BY_GIT","reason":"Complete HOBBES-PREFACE-STUDY-001, advance study coverage to eight of nineteen, and preserve eleven pending studies plus the omitted-text and textual-state limits."}; d["basis"]["current_revision_scope"]="production/corpus-src-116-sequential-reconstruction"; s=d["summary"]["theologico_political_item_level_status"]; s["independently_reconstructed_count_within_this_sequence"]=8; s["remaining_without_independent_sequential_study"]=11; s["completed_source_ids"]=uniq(s.get("completed_source_ids",[])+[SRC]); s["completed_witness_ids"]=uniq(s.get("completed_witness_ids",[])+[WIT]); s["completed_study_ids"]=uniq(s.get("completed_study_ids",[])+[STUDY]); s["witness_only_source_ids"]=[x for x in uniq(s.get("witness_only_source_ids",[])) if x!=SRC]; s["witness_only_witness_ids"]=[x for x in uniq(s.get("witness_only_witness_ids",[])) if x!=WIT]; d["summary"]["completed_operational_units"]=uniq(d["summary"].get("completed_operational_units",[])+["HOBBES-PREFACE-STUDY-001 complete provisional sequential reconstruction with documentary-omission limit","CORPUS-STUDY-015 and FINDSET-015 typed registrations","FINDSET-129 and FINDSET-130 jurisdiction-preserving problem-local syntheses"]); d["summary"]["remaining_major_deficiencies"]=["eleven Theologico-Political writings still require independent sequential item studies"]+[x for x in uniq(d["summary"].get("remaining_major_deficiencies",[])) if not re.match(r"^(eleven|twelve|thirteen|fourteen|fifteen) Theologico-Political writings",x)]; dump(p,d)

def code_tests():
    # Normalize source-status study state for the shared complete-item validator while preserving explicit omission fields.
    p="studies/theologico-political/preface-to-hobbes-politische-wissenschaft/source-status.yaml"; d=load(p); d["termination"]["study_state"]="COMPLETE_PROVISIONAL"; d["termination"]["documentary_omission_limit"]="ACTIVE"; dump(p,d)
    # Corpus validator tables.
    p=ROOT/"corpus_registry.py"; text=p.read_text(encoding="utf-8"); registry=load("corpus/index.yaml"); witnesses={x["source_id"]:x for x in registry["reviewed_witnesses"]}; complete_ids={"CORPUS-SRC-102":("CORPUS-STUDY-011","SPINOZA-PREFACE-STUDY-001","studies/theologico-political/preface-to-spinozas-critique-of-religion/sequential-reconstruction.yaml","studies/theologico-political/preface-to-spinozas-critique-of-religion/reviewed-witness.yaml","COMPLETE_FOR_QUALIFIED_1997_PLATFORM_REFERENCE_WITNESS",True),"CORPUS-SRC-103":("CORPUS-STUDY-012","SPINOZA-TREATISE-STUDY-001","studies/theologico-political/how-to-study-spinozas-theologico-political-treatise/sequential-reconstruction.yaml","studies/theologico-political/how-to-study-spinozas-theologico-political-treatise/reviewed-witness.yaml","COMPLETE_FOR_REVIEWED_1997_COLLECTED_WITNESS",False),"CORPUS-SRC-105":("CORPUS-STUDY-009","COHEN-STUDY-001","studies/theologico-political/introductory-essay-hermann-cohen-religion-of-reason/sequential-reconstruction.yaml","studies/theologico-political/introductory-essay-hermann-cohen-religion-of-reason/reviewed-witness.yaml","COMPLETE_FOR_REVIEWED_1983_COLLECTED_WITNESS",False),"CORPUS-SRC-108":("CORPUS-STUDY-013","GENESIS-STUDY-001","studies/theologico-political/on-the-interpretation-of-genesis/sequential-reconstruction.yaml","studies/theologico-political/on-the-interpretation-of-genesis/reviewed-witness.yaml","COMPLETE_FOR_REVIEWED_1997_COLLECTED_WITNESS",False),"CORPUS-SRC-109":("CORPUS-STUDY-008","JA-STUDY-001","studies/theologico-political/jerusalem-and-athens/sequential-reconstruction.yaml",None,"COMPLETE_FOR_REVIEWED_1983_COLLECTED_WITNESS",False),"CORPUS-SRC-111":("CORPUS-STUDY-010","TALMON-STUDY-001","studies/theologico-political/review-talmon-nature-of-jewish-history/sequential-reconstruction.yaml","studies/theologico-political/review-talmon-nature-of-jewish-history/reviewed-witness.yaml","COMPLETE_FOR_REVIEWED_1983_COLLECTED_WITNESS",False),"CORPUS-SRC-113":("CORPUS-STUDY-014","PERSECUTION-INTRO-STUDY-001","studies/theologico-political/introduction-to-persecution-and-the-art-of-writing/sequential-reconstruction.yaml","studies/theologico-political/introduction-to-persecution-and-the-art-of-writing/reviewed-witness.yaml","COMPLETE_FOR_REVIEWED_1997_COLLECTED_WITNESS",False),"CORPUS-SRC-116":("CORPUS-STUDY-015",STUDY,STUDY_PATH,"studies/theologico-political/preface-to-hobbes-politische-wissenschaft/reviewed-witness.yaml","COMPLETE_FOR_REVIEWED_1997_COLLECTED_WITNESS",False)}; complete={}
    for sid,(csid,iid,spath,wpath,rstate,platform) in complete_ids.items():
        w=witnesses[sid]; spec={"status_id":sid.replace("CORPUS-SRC","CORPUS-STATUS"),"witness_id":w["witness_id"],"study_id":csid,"internal_study_id":iid,"study_path":spath,"witness_record_path":wpath,"printed_page_range":w["printed_page_range"],"pdf_page_range_one_based":w["pdf_page_range_one_based"],"reading_state":rstate,"platform_reference":platform};
        if platform: spec["platform_object_identifier"]=w["platform_object_identifier"]
        complete[sid]=spec
    wonly={}
    for n in range(101,120):
        sid=f"CORPUS-SRC-{n:03d}"
        if sid in complete: continue
        w=witnesses[sid]; wonly[sid]={"status_id":f"CORPUS-STATUS-{n:03d}","witness_id":f"CORPUS-WIT-{n:03d}","witness_record_path":w["witness_record_path"],"printed_page_range":w["printed_page_range"],"pdf_page_range_one_based":w["pdf_page_range_one_based"],"container_sha256":w["container_sha256"],"container_file_size_bytes":w["container_file_size_bytes"],"container_page_count":w["container_page_count"]}
    region="COMPLETE_TP_ITEMS: dict[str, dict[str, Any]] = "+pformat(complete,width=110,sort_dicts=False)+"\n\nWITNESS_ONLY_TP_ITEMS: dict[str, dict[str, Any]] = "+pformat(wonly,width=110,sort_dicts=False)+"\n\n\n"; text,n=re.subn(r"COMPLETE_TP_ITEMS: dict\[str, dict\[str, Any\]\] = \{.*?\n\nclass CorpusRegistryError",region+"class CorpusRegistryError",text,count=1,flags=re.S); assert n==1; text=text.replace('identity.get("version") != "1.15.0"','identity.get("version") != "1.16.0"').replace('identity.version must be 1.15.0','identity.version must be 1.16.0').replace('"study records": (len(study_ids), 14)','"study records": (len(study_ids), 15)').replace('"theologico_political_independent_item_studies_registered": 7','"theologico_political_independent_item_studies_registered": 8').replace('!= "INCOMPLETE_7_OF_19"','!= "INCOMPLETE_8_OF_19"').replace('must be INCOMPLETE_7_OF_19','must be INCOMPLETE_8_OF_19'); p.write_text(text,encoding="utf-8")
    p=ROOT/"findings_registry.py"; text=p.read_text(encoding="utf-8"); synth=sorted(str(x.relative_to(ROOT)) for x in (ROOT/"problems").glob("*/synthesis/*.yaml") if x.is_file()); settext="EXPECTED_SYNTHESIS_PATHS = {\n"+"".join(f'    "{x}",\n' for x in synth)+"}\n\n"; text,n=re.subn(r"EXPECTED_SYNTHESIS_PATHS = \{.*?\n\}\n\n",settext,text,count=1,flags=re.S); assert n==1; text=text.replace('    "CORPUS-SRC-113",\n]','    "CORPUS-SRC-113",\n    "CORPUS-SRC-116",\n]').replace('"CORPUS-SRC-111", "CORPUS-SRC-113"}','"CORPUS-SRC-111", "CORPUS-SRC-113", "CORPUS-SRC-116"}'); contract='''    "FINDSET-015": {\n        "source_id": "CORPUS-SRC-116",\n        "local_syntheses": ["FINDSET-129", "FINDSET-130"],\n        "problem_bindings": {"FINDSET-129": "theologico-political", "FINDSET-130": "ancients-vs-moderns"},\n        "required_limits": {"witness_id": "CORPUS-WIT-116", "omitted_text_review": "INCOMPLETE", "independent_corroboration": "INCOMPLETE"},\n    },\n''';
    if '"FINDSET-015": {' not in text: text=text.replace('\n}\n\n\nclass FindingsRegistryError','\n'+contract+'}\n\n\nclass FindingsRegistryError',1)
    text=text.replace('identity.get("version") != "1.7.0"','identity.get("version") != "1.8.0"').replace('identity.version must be 1.7.0','identity.version must be 1.8.0').replace('if len(finding_ids) != 47:','if len(finding_ids) != 50:').replace('expected 47 finding sets','expected 50 finding sets'); p.write_text(text,encoding="utf-8")
    reps={"tests/test_corpus_registry.py":{"1.15.0":"1.16.0","54,":"55,",'study_records_registered"], 14':'study_records_registered"], 15',"test_twelve_tp_sources_have_witnesses_but_still_require_study":"test_eleven_tp_sources_have_witnesses_but_still_require_study","self.assertEqual(len(sources), 12)":"self.assertEqual(len(sources), 11)"},"tests/test_findings_registry.py":{"1.7.0":"1.8.0","len(finding_ids), 47":"len(finding_ids), 50","len(registered), 28":"len(registered), 30","len(registered), 14":"len(registered), 15"},"tests/test_interface_consistency.py":{"seven_study":"eight_study",'study_count"], 7':'study_count"], 8','sequence"], 7':'sequence"], 8','study"], 7':'study"], 8','study"], 12':'study"], 11',"INCOMPLETE_7_OF_19":"INCOMPLETE_8_OF_19",'next_item_study"], "CORPUS-SRC-116"':'next_item_study"], "CORPUS-SRC-101"','"PERSECUTION-INTRO-STUDY-001"]':'"PERSECUTION-INTRO-STUDY-001", "HOBBES-PREFACE-STUDY-001"]'},"tests/test_pr21_talmon_completion.py":{"1.11.0":"1.12.0","2.9.0":"3.0.0","1.13.0":"1.14.0","1.15.0":"1.16.0","1.7.0":"1.8.0",'study_count"], 7':'study_count"], 8','study"], 12':'study"], 11','next_item_study"], "CORPUS-SRC-116"':'next_item_study"], "CORPUS-SRC-101"','"PERSECUTION-INTRO-STUDY-001"]':'"PERSECUTION-INTRO-STUDY-001", "HOBBES-PREFACE-STUDY-001"]'},"tests/test_tp_witness_coverage_complete.py":{"INCOMPLETE_7_OF_19":"INCOMPLETE_8_OF_19",'theologico_political_independent_item_studies_registered"], 7':'theologico_political_independent_item_studies_registered"], 8',"test_twelve_witness_only_items_remain_noncertified_and_unstudied":"test_eleven_witness_only_items_remain_noncertified_and_unstudied","self.assertEqual(len(witness_only), 12)":"self.assertEqual(len(witness_only), 11",'"CORPUS-SRC-113"}':'"CORPUS-SRC-113", "CORPUS-SRC-116"}'},"tests/test_corpus_wit_102_platform_registration.py":{"INCOMPLETE_7_OF_19":"INCOMPLETE_8_OF_19"}}
    for path,rr in reps.items():
        pp=ROOT/path; tt=pp.read_text(encoding="utf-8")
        for a,b in rr.items(): tt=tt.replace(a,b)
        pp.write_text(tt,encoding="utf-8")
    # Fix typo from compact replacement if present.
    pp=ROOT/"tests/test_tp_witness_coverage_complete.py"; tt=pp.read_text(encoding="utf-8").replace('self.assertEqual(len(witness_only), 11\n','self.assertEqual(len(witness_only), 11)\n'); pp.write_text(tt,encoding="utf-8")
    # Add explicit corpus and findings tests.
    pp=ROOT/"tests/test_corpus_registry.py"; tt=pp.read_text(encoding="utf-8"); anchor='    def test_spinoza_preface_platform_witness_and_study_are_registered(self) -> None:\n';
    if 'def test_hobbes_preface_witness_and_study_preserve_omitted_text_limit' not in tt:
        block='''    def test_hobbes_preface_witness_and_study_preserve_omitted_text_limit(self) -> None:\n        registry = corpus_registry.load_registry()\n        source = next(item for item in registry["source_entities"] if item["source_id"] == "CORPUS-SRC-116")\n        entry = next(item for item in registry["source_status_records"] if item["source_id"] == "CORPUS-SRC-116")\n        study = next(item for item in registry["study_records"] if item["study_id"] == "CORPUS-STUDY-015")\n        status = corpus_registry.load_yaml(corpus_registry._resolve(entry["path"]))\n        record = corpus_registry.load_yaml(corpus_registry._resolve(study["path"]))\n        self.assertEqual(source["study_records"], ["CORPUS-STUDY-015"])\n        self.assertEqual(status["status"]["independent_sequential_study"], "HOBBES-PREFACE-STUDY-001")\n        self.assertEqual(status["termination"]["study_state"], "COMPLETE_PROVISIONAL")\n        self.assertEqual(status["termination"]["documentary_omission_limit"], "ACTIVE")\n        self.assertEqual(record["termination"]["source_reconstruction_state"], "COMPLETE_PROVISIONAL_WITH_DOCUMENTARY_OMISSION_LIMIT")\n        self.assertEqual(record["termination"]["successor_effect"], "NONE")\n\n'''; tt=tt.replace(anchor,block+anchor)
    pp.write_text(tt,encoding="utf-8")
    pp=ROOT/"tests/test_findings_registry.py"; tt=pp.read_text(encoding="utf-8"); anchor='    def test_indexes_are_derived_from_finding_set_bindings(self) -> None:\n';
    if 'def test_hobbes_preface_study_and_two_local_syntheses_preserve_documentary_limit' not in tt:
        block='''    def test_hobbes_preface_study_and_two_local_syntheses_preserve_documentary_limit(self) -> None:\n        study = self._assert_source_derivation(study_id="FINDSET-015", source_id="CORPUS-SRC-116", local_syntheses=[("FINDSET-129", "theologico-political"), ("FINDSET-130", "ancients-vs-moderns")])\n        self.assertEqual(study["witness_id"], "CORPUS-WIT-116")\n        self.assertEqual(study["omitted_text_review"], "INCOMPLETE")\n        self.assertEqual(study["successor_effect"], "NONE")\n\n'''; tt=tt.replace(anchor,block+anchor)
    pp.write_text(tt,encoding="utf-8")
    pp=ROOT/"tests/test_interface_consistency.py"; tt=pp.read_text(encoding="utf-8");
    if '"FINDSET-015":' not in tt: tt=tt.replace('"FINDSET-014": [("FINDSET-127", "theologico-political"), ("FINDSET-128", "wise-vs-vulgar")],','"FINDSET-014": [("FINDSET-127", "theologico-political"), ("FINDSET-128", "wise-vs-vulgar")],\n            "FINDSET-015": [("FINDSET-129", "theologico-political"), ("FINDSET-130", "ancients-vs-moderns")],')
    pp.write_text(tt,encoding="utf-8")

def main(): corpus(); findings(); other(); code_tests(); print("Materialized CORPUS-SRC-116 complete provisional study integration.")
if __name__=="__main__": main()
